### ISSUE TITLE
Can't install django global permissions on docker images [UnicodeDecodeError: 'ascii' codec]

### ISSUE THREAD

**Issue by aisabellafontes** [eduardo-matos/django-global-permissions#9]
Hi,

I tried to install the latest version of Django-global-permissions packages (one of the packages of requirements.txt) from my Django docker image and always return this error. 
I tried to run inside the image with docker exec but the same issue occurred. So, I just clone the source of this project, fixed the error just removing the line that read README.md file. What Else Can I do?

Issue below:

```
 ---> Running in 60653d57a501
Traceback (most recent call last):
  File "/src/django-global-permissions/setup.py", line 20, in <module>
    readme = open('README.md').read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1458: ordinal not in range(128)
ERROR: Service 'django' failed to build: The command '/bin/sh -c python3 /src/django-global-permissions/setup.py install' returned a non-zero code: 1
```

**Comment by eduardo-matos** [comment]
I'll fix this issue asap and publish a patch to PyPI.

Thanks for reporting!

**Comment by eduardo-matos** [comment]
@aisabellafontes 
Which Python version were you running?
Are you using a public docker base image? If yes, which one?

**Comment by aisabellafontes** [comment]
HI @eduardo-matos 

I'm using a private docker image (private company source, unfortunately). So, is python3.5

**Comment by eduardo-matos** [comment]
@aisabellafontes I tried to install this package on the [python:3.5](https://hub.docker.com/_/python/) image, and it worked just fine.

Are you installing the latest version (0.2.3)?

**Comment by aisabellafontes** [comment]
Hi @eduardo-matos,

Yes, I just install the latest version. But the original docker images was from ubuntu:16.04 docker image. I'll try to install from a docker python:3-5 images for testing.

**Comment by ecascardo** [comment]
Hi @eduardo-matos, 
This issue is fixed in https://github.com/eduardo-matos/django-global-permissions/pull/10

**Comment by eduardo-matos** [comment]
Released [version 0.2.4 at PyPI](https://pypi.org/project/django-global-permissions/0.2.4/).
